---
version: 20.07

identity:
  oidc:
    client_id: $CLIENT_ID
    client_secret: $CLIENT_SECRET
    discovery_endpoint: "https://demo1.ice.ibmcloud.com/oidc/endpoint/default/.well-known/openid-configuration"